# tfsec configuration to reduce noise and focus on important security issues

# Set minimum severity to HIGH to significantly reduce output
minimum_severity: HIGH

# Exclude checks that are not applicable to our use case
exclude:
  # GCS bucket checks - we need public access for static website hosting
  - google-storage-enable-ubla
  - google-storage-bucket-encryption-customer-key
  - google-storage-no-public-access
  
  # Compute checks that don't apply to static hosting
  - google-compute-enable-shielded-vm-vtpm
  - google-compute-enable-shielded-vm-im
  - google-compute-enable-vpc-flow-logs
  - google-compute-no-public-ip
  
  # IAM checks that are intentional for public static hosting
  - google-iam-no-public-access
  
  # General checks
  - general-secrets-sensitive-in-variable
  - general-secrets-sensitive-in-local

# Ignore test/example files
exclude_paths:
  - "**/test/**"
  - "**/tests/**"
  - "**/examples/**"
  - "**/*.example"